import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar
    "nav.overview": "Overview",
    "nav.models": "My Furniture",
    "nav.rooms": "My Rooms",
    "nav.layouts": "Saved Layouts",
    "nav.profile": "Profile",
    "nav.billing": "Billing",
    "nav.settings": "Settings",
    "nav.editor": "Room Editor",
    "nav.furniture": "Furniture Library",
    "nav.aiGenerator": "AI Generator",
    "nav.roomScan": "Room Scan AI",

    // Topbar
    "topbar.dashboard": "Dashboard",
    "topbar.uploadModel": "Upload Model",
    "topbar.createRoom": "Create Room",

    // Profile dropdown
    "profile.logout": "Log Out",

    // Dashboard Overview
    "overview.title": "Your AR Workspace",
    "overview.subtitle": "Design, visualize, and optimize interior spaces",
    "overview.createLayout": "Create Layout",
    "overview.addFurniture": "Add Furniture",
    "overview.aiLayout": "AI Layout",
    "overview.stats.models": "Models",
    "overview.stats.rooms": "Rooms",
    "overview.stats.layouts": "Layouts",
    "overview.stats.furniture": "Furniture",
    "overview.stats.ai": "AI Suggestions",
    "overview.quickActions": "Quick Actions",
    "overview.recentActivity": "Recent Activity",
    "overview.viewAll": "View all activity",
    "overview.launchAR": "Launch AR Session",
    "overview.launchAR.desc": "Place furniture in your real room",
    "overview.aiOptimizer": "AI Space Optimizer",
    "overview.aiOptimizer.desc": "Automatically optimize room layout",
    "overview.upgradePlan": "Upgrade Plan",
    "overview.upgradePlan.desc": "Unlock AI features and unlimited resources",
    "overview.used": "used",
    "overview.startAR": "Start AR Session",
    "overview.addFurniture.desc": "Upload images and generate 3D furniture",
    "overview.recentRooms": "Recent Rooms",
    "overview.items": "items",
    "overview.stats.models.desc": "Furniture objects in your library",
    "overview.stats.rooms.desc": "Active room projects",
    "overview.stats.layouts.desc": "Saved AR configurations",
    "overview.stats.furniture.desc": "Total furniture in your catalog",
    "overview.stats.ai.desc": "AI-powered suggestions used",

    // Hero quick buttons
    "hero.uploadModel": "Upload Model",
    "hero.newRoom": "New Room",
    "hero.aiGenerate": "AI Generate",

    // Quick action descriptions
    "overview.createLayout.desc": "Start a new room layout in the editor",

    // Workflow
    "workflow.title": "Your Design Workflow",
    "workflow.upload": "Upload Model",
    "workflow.createRoom": "Create Room",
    "workflow.arrange": "Arrange Layout",
    "workflow.viewAR": "View in AR",

    // Activity
    "activity.uploadedSofa": "Uploaded Modern Sofa model",
    "activity.createdLayout": "Created living room layout",
    "activity.arSession": "AR session completed",
    "activity.editedRoom": "Edited bedroom layout",
    "activity.2hAgo": "2 hours ago",
    "activity.5hAgo": "5 hours ago",
    "activity.yesterday": "Yesterday",
    "activity.2dAgo": "2 days ago",

    // Recent Rooms
    "rooms.recent.living": "Living Room",
    "rooms.recent.bedroom": "Master Bedroom",
    "rooms.recent.office": "Home Office",

    // My Models / Furniture
    "models.title": "My Furniture",
    "models.subtitle": "Upload images to generate 3D furniture objects",
    "models.add": "Add Furniture",
    "models.search": "Search furniture…",
    "models.empty": "No custom furniture yet",
    "models.emptyDesc": "Upload an image and generate a 3D model to get started.",
    "models.noResults": "No results found",
    "models.noResultsDesc": "Try a different search term.",

    // My Rooms
    "rooms.title": "My Rooms",
    "rooms.subtitle": "Create and manage room spaces",
    "rooms.create": "Create Room",
    "rooms.search": "Search rooms…",
    "rooms.layouts": "layouts",
    "rooms.empty": "No rooms yet. Create your first room to get started!",
    "rooms.noResults": "No rooms match your search",
    "rooms.emptyDesc": "Design and manage your rooms with our 3D editor",
    "rooms.noResultsDesc": "Try a different search term",
    "rooms.allRooms": "All Rooms",
    "rooms.openEditor": "Open Editor",
    "rooms.viewLayouts": "View Layouts",
    "rooms.delete": "Delete",
    "rooms.savedLayouts": "Saved Layouts",
    "rooms.noLayouts": "No layouts saved yet",
    "rooms.noLayoutsDesc": "Open the editor and hit Save to create your first layout",
    "rooms.objects": "objects",
    "rooms.createNew": "Create New Room",
    "rooms.roomName": "Room Name",
    "rooms.roomNamePlaceholder": "e.g. Living Room",
    "rooms.width": "Width",
    "rooms.depth": "Depth",
    "rooms.height": "Height",
    "rooms.cancel": "Cancel",
    "rooms.createOpen": "Create & Open Editor",
    "rooms.created": "Room Created",
    "rooms.deleted": "Deleted",
    "rooms.removed": "removed",

    // Saved Layouts
    "layouts.title": "Saved Layouts",
    "layouts.subtitle": "Your saved AR room configurations",
    "layouts.new": "New Layout",
    "layouts.search": "Search layouts…",
    "layouts.objects": "objects",
    "layouts.empty": "No saved layouts yet. Save a layout from the Room Editor!",
    "layouts.noResults": "No layouts match your search",
    "layouts.openEditor": "Open in Editor",
    "layouts.delete": "Delete",

    // Furniture Library
    "furnitureLib.title": "Furniture Library",
    "furnitureLib.subtitle": "Browse, search, and manage your furniture catalog",
    "furnitureLib.search": "Search furniture by name, tag, or material…",
    "furnitureLib.category": "Category",
    "furnitureLib.style": "Style",
    "furnitureLib.favorites": "Favorites",
    "furnitureLib.items": "items",
    "furnitureLib.empty": "No furniture found matching your filters",
    "furnitureLib.previewAR": "Preview in AR",

    // Profile
    "profile.title": "Profile",
    "profile.subtitle": "Manage your account and preferences",
    "profile.tab.account": "Account",
    "profile.tab.plan": "Plan & Usage",
    "profile.tab.billing": "Billing",
    "profile.tab.preferences": "Preferences",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.password": "Password",
    "profile.save": "Save Changes",
    "profile.deleteAccount": "Delete Account",
    "profile.paymentMethod": "Payment Method",
    "profile.noPayment": "No payment method on file",
    "profile.invoiceHistory": "Invoice History",
    "profile.noInvoices": "No invoices yet",
    "profile.currentPlan": "Current Plan",
    "profile.unlimited": "unlimited",
    "profile.theme": "Theme",
    "profile.themeDesc": "Application color theme",
    "profile.autoSave": "Auto-save layouts",
    "profile.autoSaveDesc": "Automatically save layout changes",
    "profile.emailNotif": "Email notifications",
    "profile.emailNotifDesc": "Receive updates and tips via email",
    "profile.currency": "Currency",
    "profile.currencyDesc": "Display currency for pricing",
    "profile.language": "Language",
    "profile.languageDesc": "Choose your preferred language",
    "profile.perMonth": "/mo",
    "profile.theme.dark": "Dark",
    "profile.theme.light": "Light",
    "profile.unit": "Unit",
    "profile.unitToggle": "cm/m",

    // Billing
    "billing.title": "Billing",
    "billing.subtitle": "Manage your subscription and payments",
    "billing.upgrade": "Upgrade Plan",
    "billing.cancel": "Cancel Subscription",
    "billing.creditUsage": "AI Credit Usage",
    "billing.creditsUsedLabel": "used",
    "billing.creditsRemaining": "credits remaining",
    "billing.buyMore": "Buy more credits",
    "billing.aiRequests": "AI Requests",
    "billing.remaining": "Remaining",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Application and workspace settings",
    "settings.tab.notifications": "Notifications",
    "settings.tab.security": "Security",
    "settings.tab.data": "Data",
    "settings.notif.email": "Email notifications",
    "settings.notif.emailDesc": "Receive updates about your account and projects",
    "settings.notif.marketing": "Marketing emails",
    "settings.notif.marketingDesc": "Tips, tutorials, and product updates",
    "settings.notif.layoutSaved": "Layout saved alerts",
    "settings.notif.layoutSavedDesc": "Get notified when layouts are auto-saved",
    "settings.security.changePassword": "Change Password",
    "settings.security.currentPassword": "Current password",
    "settings.security.newPassword": "New password",
    "settings.security.confirmPassword": "Confirm new password",
    "settings.security.update": "Update Password",
    "settings.security.twoFactor": "Two-factor authentication",
    "settings.security.twoFactorDesc": "Add extra security to your account",
    "settings.security.enable2FA": "Enable 2FA",
    "settings.security.sessions": "Active Sessions",
    "settings.security.sessionsDesc": "Manage devices logged into your account",
    "settings.security.currentSession": "Current session",
    "settings.security.logoutAll": "Log out all other sessions",
    "settings.data.export": "Export Data",
    "settings.data.exportDesc": "Download all your rooms, layouts, and furniture data",
    "settings.data.exportBtn": "Export as JSON",
    "settings.data.delete": "Delete All Data",
    "settings.data.deleteDesc": "Permanently remove all your data. This action cannot be undone.",
    "settings.data.deleteBtn": "Delete all data",
    "settings.data.cache": "Clear Cache",
    "settings.data.cacheDesc": "Clear local cache and temporary files",
    "settings.data.cacheBtn": "Clear cache",

    // Add Furniture Modal
    "furniture.add": "Add Furniture",
    "furniture.details": "Object Details",
    "furniture.preview": "3D Preview",
    "furniture.upload.desc": "Upload a photo of any furniture piece. We'll use it to generate a 3D object for AR placement.",
    "furniture.upload.cta": "Click to upload or drag & drop",
    "furniture.upload.hint": "JPG, PNG, or WEBP • Max 10MB",
    "furniture.name": "Object Name",
    "furniture.category": "Category",
    "furniture.material": "Material",
    "furniture.dimensions": "Dimensions",
    "furniture.shape": "Base Shape",
    "furniture.generate": "Generate 3D Object",
    "furniture.generating": "Generating…",
    "furniture.back": "Back",
    "furniture.editDetails": "Edit Details",
    "furniture.save": "Save to Library",
    "furniture.saved": "Furniture saved!",
    "furniture.savedDesc": "has been added to your library.",
    "furniture.invalidFile": "Invalid file",
    "furniture.invalidFileDesc": "Please upload an image file (JPG, PNG, WEBP).",

    // Room Scan
    "roomScan.title": "Room Scan AI",
    "roomScan.subtitle": "Upload a photo to auto-detect room structure",
    "roomScan.uploadTitle": "Upload Room Photo",
    "roomScan.uploadDesc": "Take a photo of your room or drag and drop an image here. AI will detect walls, floor, and room boundaries.",
    "roomScan.choosePhoto": "Choose Photo",
    "roomScan.fileHint": "Supports JPG, PNG, WEBP • Max 20MB",
    "roomScan.tipWide": "Wide angle",
    "roomScan.tipWideDesc": "Capture the full room",
    "roomScan.tipLight": "Good lighting",
    "roomScan.tipLightDesc": "Ensure walls are visible",
    "roomScan.tipClear": "Clear floor",
    "roomScan.tipClearDesc": "Less clutter = better scan",
    "roomScan.analyzing": "Analyzing Room Structure",
    "roomScan.analyzingDesc": "Detecting walls, floor boundaries, and room dimensions…",
    "roomScan.complete": "complete",
    "roomScan.stepFloor": "Detecting floor plane",
    "roomScan.stepWalls": "Identifying wall boundaries",
    "roomScan.stepDimensions": "Calculating dimensions",
    "roomScan.stepModel": "Generating room model",
    "roomScan.detected": "Room Detected",
    "roomScan.confidence": "confidence",
    "roomScan.detectedTitle": "Detected Room Structure",
    "roomScan.width": "Width",
    "roomScan.depth": "Depth",
    "roomScan.height": "Height",
    "roomScan.uploadAnother": "Upload Another",
    "roomScan.useLayout": "Use This Layout",

    // AI Credits
    "ai.creditsLeft": "credits left",
    "ai.noCredits": "Not enough credits",
    "ai.noCreditsDesc": "You don't have enough AI credits. Please upgrade your plan.",
    "ai.notEnoughCredits": "Not Enough Credits — Upgrade Plan",
    "ai.comingSoon": "Coming Soon",
    "ai.feature.layoutSuggest": "AI Layout Suggest",
    "ai.feature.layoutSuggestDesc": "Generate optimized furniture layouts for any room type",
    "ai.feature.styleTransform": "AI Style Transform",
    "ai.feature.styleTransformDesc": "Transform your room into a different design style",
    "ai.feature.productRecommend": "AI Product Recommend",
    "ai.feature.productRecommendDesc": "Get furniture recommendations based on your room",
    "ai.feature.budgetOptimize": "AI Budget Optimize",
    "ai.feature.budgetOptimizeDesc": "Optimize your interior design within your budget",
    "ai.feature.photoRender": "AI Photorealistic Render",
    "ai.feature.photoRenderDesc": "Generate photorealistic images of your room design",
    "ai.feature.fullRedesign": "AI Full Room Redesign",
    "ai.feature.fullRedesignDesc": "Complete room redesign with AI-powered suggestions",
    // AI Tool UI keys
    "ai.currentStyle": "Current Style",
    "ai.targetStyle": "Target Style",
    "ai.transform": "Transform Style",
    "ai.transforming": "Transforming Style...",
    "ai.transformingDesc": "Applying style transformation to your room",
    "ai.styleResults": "Style Transformation Results",
    "ai.tryAgain": "Try Again",
    "ai.roomContext": "Room Context",
    "ai.preferences": "Preferences",
    "ai.getRecommendations": "Get Recommendations",
    "ai.findingProducts": "Finding Products...",
    "ai.recommendations": "Recommended Products",
    "ai.totalBudget": "Total Budget",
    "ai.priority": "Optimization Priority",
    "ai.optimizeBudget": "Optimize Budget",
    "ai.optimizingBudget": "Optimizing Budget...",
    "ai.budgetResults": "Budget Optimization",
    "ai.renderStyle": "Render Style",
    "ai.lighting": "Lighting",
    "ai.resolution": "Resolution",
    "ai.startRender": "Start Render",
    "ai.rendering": "Rendering...",
    "ai.renderingDesc": "Creating photorealistic image of your design",
    "ai.renderResult": "Render Complete",
    "ai.renderAnother": "Render Another",
    "ai.redesignScope": "Redesign Scope",
    "ai.designVision": "Your Design Vision",
    "ai.startRedesign": "Start Full Redesign",
    "ai.redesigning": "Redesigning Room...",
    "ai.redesigningDesc": "AI is reimagining your entire space",
    "ai.proposedChanges": "Proposed Changes",
    // AI Optimize (Editor)
    "ai.opt.title": "AI Optimize",
    "ai.opt.analyzeTitle": "Analyze Your Layout",
    "ai.opt.analyzeDesc": "AI will analyze your furniture arrangement and suggest improvements for flow, aesthetics, and space efficiency.",
    "ai.opt.objectsInRoom": "objects in room",
    "ai.opt.optimize": "Optimize Layout",
    "ai.opt.addFirst": "Add some furniture first to optimize",
    "ai.opt.analyzing": "Analyzing layout...",
    "ai.opt.analyzingDesc": "Checking flow, spacing, and aesthetics",
    "ai.opt.suggestionsFound": "suggestions",
    "ai.opt.reanalyze": "Re-analyze",
    "ai.opt.applied": "Applied",
    "ai.opt.moveForFlow": "Improve traffic flow",
    "ai.opt.moveForFlowDesc": "Move furniture towards the wall for better walking space",
    "ai.opt.rotateAlign": "Better alignment",
    "ai.opt.rotateAlignDesc": "Rotate furniture to face the room center for conversation flow",
    "ai.opt.addPlant": "Add greenery",
    "ai.opt.addPlantDesc": "The far corner is underutilized — adding a plant would balance the composition",

    "aiGen.title": "AI Layout Generator",
    "aiGen.subtitle": "Generate optimized room layouts powered by AI",
    "aiGen.roomType": "Room Type",
    "aiGen.designStyle": "Design Style",
    "aiGen.dimensions": "Room Dimensions",
    "aiGen.widthLabel": "Width (m)",
    "aiGen.depthLabel": "Depth (m)",
    "aiGen.totalArea": "m² total",
    "aiGen.advanced": "Advanced Options",
    "aiGen.selected": "selected",
    "aiGen.occupants": "Number of Occupants",
    "aiGen.budget": "Budget Range",
    "aiGen.purpose": "Primary Purpose",
    "aiGen.selectMultiple": "(select multiple)",
    "aiGen.mustHave": "Must-Have Furniture",
    "aiGen.customPrompt": "Custom Prompt",
    "aiGen.optional": "(optional)",
    "aiGen.promptPlaceholder": "e.g. I want a cozy reading nook by the window, TV facing the sofa, and space for a yoga mat...",
    "aiGen.promptHint": "Describe your preferences, requirements, or specific furniture arrangements you'd like the AI to consider.",
    "aiGen.generate": "Generate AI Layouts",
    "aiGen.generating": "Generating Layouts",
    "aiGen.generatingDesc": "AI is analyzing your room and creating optimal furniture arrangements…",
    "aiGen.analyzingDim": "🔍 Analyzing dimensions",
    "aiGen.selectingFurn": "🪑 Selecting furniture",
    "aiGen.optimizing": "📐 Optimizing placement",
    "aiGen.suggestions": "AI Suggestions",
    "aiGen.suggestionsDesc": "layout options generated for your",
    "aiGen.regenerate": "Regenerate",
    "aiGen.bestMatch": "Best Match",
    "aiGen.apply": "Apply",
    "aiGen.edit": "Edit",
    "aiGen.spaceAnalysis": "Space Analysis",
    "aiGen.spaceEfficiency": "Space Efficiency",
    "aiGen.walkingPaths": "Walking Paths",
    "aiGen.unusedArea": "Unused Area",
    "aiGen.furnitureDensity": "Furniture Density",
    "aiGen.clear": "Clear",
    "aiGen.optimal": "Optimal",
    "aiGen.layoutApplied": "Layout Applied",

    // Plan & Credits
    "plan.plan": "Plan",
    "plan.credits": "AI Credits",
    "plan.creditsRemaining": "remaining",
    "plan.creditsUsed": "used",
    "plan.currentPlan": "Current Plan",
    "plan.viewPlans": "View Plans",
    "plan.free": "Free",
    "plan.basic": "Basic",
    "plan.advanced": "Advanced",
    "plan.pro": "Pro",
    "plan.perDay": "/day",
    "plan.noCredits": "No credits left",
    "plan.buyMore": "Get More Credits",

    // Mobile nav
    "mobile.home": "Home",
    "mobile.models": "Models",
    "mobile.rooms": "Rooms",
    "mobile.profile": "Profile",
  },
  vi: {
    // Sidebar
    "nav.overview": "Tổng quan",
    "nav.models": "Nội thất",
    "nav.rooms": "Phòng",
    "nav.layouts": "Bố cục đã lưu",
    "nav.profile": "Hồ sơ",
    "nav.billing": "Thanh toán",
    "nav.settings": "Cài đặt",
    "nav.editor": "Trình chỉnh sửa",
    "nav.furniture": "Thư viện nội thất",
    "nav.aiGenerator": "AI Tạo bố cục",
    "nav.roomScan": "Quét phòng AI",

    // Topbar
    "topbar.dashboard": "Bảng điều khiển",
    "topbar.uploadModel": "Tải mô hình",
    "topbar.createRoom": "Tạo phòng",

    // Profile dropdown
    "profile.logout": "Đăng xuất",

    // Dashboard Overview
    "overview.title": "Không gian AR của bạn",
    "overview.subtitle": "Thiết kế, trực quan hóa và tối ưu hóa không gian nội thất",
    "overview.createLayout": "Tạo bố cục",
    "overview.addFurniture": "Thêm nội thất",
    "overview.aiLayout": "Bố cục AI",
    "overview.stats.models": "Mô hình",
    "overview.stats.rooms": "Phòng",
    "overview.stats.layouts": "Bố cục",
    "overview.stats.furniture": "Nội thất",
    "overview.stats.ai": "Gợi ý AI",
    "overview.quickActions": "Thao tác nhanh",
    "overview.recentActivity": "Hoạt động gần đây",
    "overview.viewAll": "Xem tất cả",
    "overview.launchAR": "Mở phiên AR",
    "overview.launchAR.desc": "Đặt nội thất vào phòng thực tế",
    "overview.aiOptimizer": "Tối ưu không gian AI",
    "overview.aiOptimizer.desc": "Tự động tối ưu bố cục phòng",
    "overview.upgradePlan": "Nâng cấp gói",
    "overview.upgradePlan.desc": "Mở khóa tính năng AI và tài nguyên không giới hạn",
    "overview.used": "đã dùng",
    "overview.startAR": "Mở phiên AR",
    "overview.addFurniture.desc": "Tải ảnh lên và tạo nội thất 3D",
    "overview.recentRooms": "Phòng gần đây",
    "overview.items": "đối tượng",
    "overview.stats.models.desc": "Đối tượng nội thất trong thư viện",
    "overview.stats.rooms.desc": "Dự án phòng đang hoạt động",
    "overview.stats.layouts.desc": "Cấu hình AR đã lưu",
    "overview.stats.furniture.desc": "Tổng nội thất trong danh mục",
    "overview.stats.ai.desc": "Gợi ý AI đã sử dụng",

    // Hero quick buttons
    "hero.uploadModel": "Tải mô hình",
    "hero.newRoom": "Tạo phòng",
    "hero.aiGenerate": "AI Tạo bố cục",

    // Quick action descriptions
    "overview.createLayout.desc": "Tạo bố cục phòng mới trong trình chỉnh sửa",

    // Workflow
    "workflow.title": "Quy trình thiết kế",
    "workflow.upload": "Tải mô hình",
    "workflow.createRoom": "Tạo phòng",
    "workflow.arrange": "Sắp xếp bố cục",
    "workflow.viewAR": "Xem trong AR",

    // Activity
    "activity.uploadedSofa": "Đã tải lên mô hình Sofa hiện đại",
    "activity.createdLayout": "Đã tạo bố cục phòng khách",
    "activity.arSession": "Phiên AR đã hoàn thành",
    "activity.editedRoom": "Đã chỉnh sửa bố cục phòng ngủ",
    "activity.2hAgo": "2 giờ trước",
    "activity.5hAgo": "5 giờ trước",
    "activity.yesterday": "Hôm qua",
    "activity.2dAgo": "2 ngày trước",

    // Recent Rooms
    "rooms.recent.living": "Phòng khách",
    "rooms.recent.bedroom": "Phòng ngủ chính",
    "rooms.recent.office": "Phòng làm việc",

    // My Models / Furniture
    "models.title": "Nội thất của tôi",
    "models.subtitle": "Tải ảnh lên để tạo đối tượng 3D nội thất",
    "models.add": "Thêm nội thất",
    "models.search": "Tìm kiếm nội thất…",
    "models.empty": "Chưa có nội thất tùy chỉnh",
    "models.emptyDesc": "Tải ảnh lên và tạo mô hình 3D để bắt đầu.",
    "models.noResults": "Không tìm thấy kết quả",
    "models.noResultsDesc": "Thử từ khóa tìm kiếm khác.",

    // My Rooms
    "rooms.title": "Phòng của tôi",
    "rooms.subtitle": "Tạo và quản lý không gian phòng",
    "rooms.create": "Tạo phòng",
    "rooms.search": "Tìm kiếm phòng…",
    "rooms.layouts": "bố cục",
    "rooms.empty": "Chưa có phòng nào. Tạo phòng đầu tiên để bắt đầu!",
    "rooms.noResults": "Không tìm thấy phòng phù hợp",
    "rooms.emptyDesc": "Thiết kế và quản lý phòng của bạn với trình chỉnh sửa 3D",
    "rooms.noResultsDesc": "Thử từ khóa tìm kiếm khác",
    "rooms.allRooms": "Tất cả phòng",
    "rooms.openEditor": "Mở trình chỉnh sửa",
    "rooms.viewLayouts": "Xem bố cục",
    "rooms.delete": "Xóa",
    "rooms.savedLayouts": "Bố cục đã lưu",
    "rooms.noLayouts": "Chưa có bố cục nào",
    "rooms.noLayoutsDesc": "Mở trình chỉnh sửa và nhấn Lưu để tạo bố cục đầu tiên",
    "rooms.objects": "đối tượng",
    "rooms.createNew": "Tạo phòng mới",
    "rooms.roomName": "Tên phòng",
    "rooms.roomNamePlaceholder": "VD: Phòng khách",
    "rooms.width": "Chiều rộng",
    "rooms.depth": "Chiều sâu",
    "rooms.height": "Chiều cao",
    "rooms.cancel": "Hủy",
    "rooms.createOpen": "Tạo & Mở trình chỉnh sửa",
    "rooms.created": "Đã tạo phòng",
    "rooms.deleted": "Đã xóa",
    "rooms.removed": "đã được xóa",

    // Saved Layouts
    "layouts.title": "Bố cục đã lưu",
    "layouts.subtitle": "Cấu hình phòng AR đã lưu của bạn",
    "layouts.new": "Bố cục mới",
    "layouts.search": "Tìm kiếm bố cục…",
    "layouts.objects": "đối tượng",
    "layouts.empty": "Chưa có bố cục nào. Lưu bố cục từ Trình chỉnh sửa!",
    "layouts.noResults": "Không tìm thấy bố cục phù hợp",
    "layouts.openEditor": "Mở trong trình chỉnh sửa",
    "layouts.delete": "Xóa",

    // Furniture Library
    "furnitureLib.title": "Thư viện nội thất",
    "furnitureLib.subtitle": "Duyệt, tìm kiếm và quản lý danh mục nội thất",
    "furnitureLib.search": "Tìm kiếm theo tên, thẻ hoặc chất liệu…",
    "furnitureLib.category": "Danh mục",
    "furnitureLib.style": "Phong cách",
    "furnitureLib.favorites": "Yêu thích",
    "furnitureLib.items": "đối tượng",
    "furnitureLib.empty": "Không tìm thấy nội thất phù hợp",
    "furnitureLib.previewAR": "Xem trong AR",

    // Profile
    "profile.title": "Hồ sơ",
    "profile.subtitle": "Quản lý tài khoản và tùy chọn",
    "profile.tab.account": "Tài khoản",
    "profile.tab.plan": "Gói & Sử dụng",
    "profile.tab.billing": "Thanh toán",
    "profile.tab.preferences": "Tùy chọn",
    "profile.name": "Tên",
    "profile.email": "Email",
    "profile.password": "Mật khẩu",
    "profile.save": "Lưu thay đổi",
    "profile.deleteAccount": "Xóa tài khoản",
    "profile.paymentMethod": "Phương thức thanh toán",
    "profile.noPayment": "Chưa có phương thức thanh toán",
    "profile.invoiceHistory": "Lịch sử hóa đơn",
    "profile.noInvoices": "Chưa có hóa đơn",
    "profile.currentPlan": "Gói hiện tại",
    "profile.unlimited": "không giới hạn",
    "profile.theme": "Giao diện",
    "profile.themeDesc": "Giao diện màu sắc ứng dụng",
    "profile.autoSave": "Tự động lưu bố cục",
    "profile.autoSaveDesc": "Tự động lưu thay đổi bố cục",
    "profile.emailNotif": "Thông báo email",
    "profile.emailNotifDesc": "Nhận cập nhật và mẹo qua email",
    "profile.currency": "Đơn vị tiền tệ",
    "profile.currencyDesc": "Đơn vị tiền hiển thị giá",
    "profile.language": "Ngôn ngữ",
    "profile.languageDesc": "Chọn ngôn ngữ ưa thích của bạn",
    "profile.perMonth": "/tháng",
    "profile.theme.dark": "Tối",
    "profile.theme.light": "Sáng",
    "profile.unit": "Đơn vị",
    "profile.unitToggle": "cm/m",

    // Billing
    "billing.title": "Thanh toán",
    "billing.subtitle": "Quản lý đăng ký và thanh toán",
    "billing.upgrade": "Nâng cấp gói",
    "billing.cancel": "Hủy đăng ký",
    "billing.creditUsage": "Sử dụng Credit AI",
    "billing.creditsUsedLabel": "đã dùng",
    "billing.creditsRemaining": "credit còn lại",
    "billing.buyMore": "Mua thêm credit",
    "billing.aiRequests": "Yêu cầu AI",
    "billing.remaining": "Còn lại",

    // Settings
    "settings.title": "Cài đặt",
    "settings.subtitle": "Cài đặt ứng dụng và không gian làm việc",
    "settings.tab.notifications": "Thông báo",
    "settings.tab.security": "Bảo mật",
    "settings.tab.data": "Dữ liệu",
    "settings.notif.email": "Thông báo email",
    "settings.notif.emailDesc": "Nhận cập nhật về tài khoản và dự án của bạn",
    "settings.notif.marketing": "Email tiếp thị",
    "settings.notif.marketingDesc": "Mẹo, hướng dẫn và cập nhật sản phẩm",
    "settings.notif.layoutSaved": "Thông báo lưu bố cục",
    "settings.notif.layoutSavedDesc": "Nhận thông báo khi bố cục được tự động lưu",
    "settings.security.changePassword": "Đổi mật khẩu",
    "settings.security.currentPassword": "Mật khẩu hiện tại",
    "settings.security.newPassword": "Mật khẩu mới",
    "settings.security.confirmPassword": "Xác nhận mật khẩu mới",
    "settings.security.update": "Cập nhật mật khẩu",
    "settings.security.twoFactor": "Xác thực hai lớp",
    "settings.security.twoFactorDesc": "Thêm lớp bảo mật cho tài khoản",
    "settings.security.enable2FA": "Bật 2FA",
    "settings.security.sessions": "Phiên đăng nhập",
    "settings.security.sessionsDesc": "Quản lý thiết bị đang đăng nhập",
    "settings.security.currentSession": "Phiên hiện tại",
    "settings.security.logoutAll": "Đăng xuất tất cả phiên khác",
    "settings.data.export": "Xuất dữ liệu",
    "settings.data.exportDesc": "Tải xuống tất cả phòng, bố cục và nội thất của bạn",
    "settings.data.exportBtn": "Xuất file JSON",
    "settings.data.delete": "Xóa toàn bộ dữ liệu",
    "settings.data.deleteDesc": "Xóa vĩnh viễn tất cả dữ liệu. Không thể hoàn tác.",
    "settings.data.deleteBtn": "Xóa toàn bộ",
    "settings.data.cache": "Xóa bộ nhớ đệm",
    "settings.data.cacheDesc": "Xóa cache và tệp tạm thời",
    "settings.data.cacheBtn": "Xóa cache",

    // Add Furniture Modal
    "furniture.add": "Thêm nội thất",
    "furniture.details": "Chi tiết đối tượng",
    "furniture.preview": "Xem trước 3D",
    "furniture.upload.desc": "Tải ảnh bất kỳ món nội thất. Chúng tôi sẽ tạo đối tượng 3D để đặt trong AR.",
    "furniture.upload.cta": "Nhấn để tải lên hoặc kéo & thả",
    "furniture.upload.hint": "JPG, PNG, hoặc WEBP • Tối đa 10MB",
    "furniture.name": "Tên đối tượng",
    "furniture.category": "Danh mục",
    "furniture.material": "Chất liệu",
    "furniture.dimensions": "Kích thước",
    "furniture.shape": "Hình dạng cơ bản",
    "furniture.generate": "Tạo đối tượng 3D",
    "furniture.generating": "Đang tạo…",
    "furniture.back": "Quay lại",
    "furniture.editDetails": "Sửa chi tiết",
    "furniture.save": "Lưu vào thư viện",
    "furniture.saved": "Đã lưu nội thất!",
    "furniture.savedDesc": "đã được thêm vào thư viện.",
    "furniture.invalidFile": "Tệp không hợp lệ",
    "furniture.invalidFileDesc": "Vui lòng tải lên tệp hình ảnh (JPG, PNG, WEBP).",

    // Room Scan
    "roomScan.title": "Quét phòng AI",
    "roomScan.subtitle": "Tải ảnh lên để tự động nhận diện cấu trúc phòng",
    "roomScan.uploadTitle": "Tải ảnh phòng lên",
    "roomScan.uploadDesc": "Chụp ảnh phòng hoặc kéo thả ảnh vào đây. AI sẽ nhận diện tường, sàn và ranh giới phòng.",
    "roomScan.choosePhoto": "Chọn ảnh",
    "roomScan.fileHint": "Hỗ trợ JPG, PNG, WEBP • Tối đa 20MB",
    "roomScan.tipWide": "Góc rộng",
    "roomScan.tipWideDesc": "Chụp toàn bộ phòng",
    "roomScan.tipLight": "Ánh sáng tốt",
    "roomScan.tipLightDesc": "Đảm bảo tường rõ ràng",
    "roomScan.tipClear": "Sàn sạch",
    "roomScan.tipClearDesc": "Ít đồ = quét tốt hơn",
    "roomScan.analyzing": "Đang phân tích cấu trúc phòng",
    "roomScan.analyzingDesc": "Nhận diện tường, ranh giới sàn và kích thước phòng…",
    "roomScan.complete": "hoàn thành",
    "roomScan.stepFloor": "Nhận diện mặt sàn",
    "roomScan.stepWalls": "Xác định ranh giới tường",
    "roomScan.stepDimensions": "Tính toán kích thước",
    "roomScan.stepModel": "Tạo mô hình phòng",
    "roomScan.detected": "Đã nhận diện phòng",
    "roomScan.confidence": "độ tin cậy",
    "roomScan.detectedTitle": "Cấu trúc phòng đã nhận diện",
    "roomScan.width": "Chiều rộng",
    "roomScan.depth": "Chiều sâu",
    "roomScan.height": "Chiều cao",
    "roomScan.uploadAnother": "Tải ảnh khác",
    "roomScan.useLayout": "Sử dụng bố cục này",

    // AI Credits
    "ai.creditsLeft": "credit còn lại",
    "ai.noCredits": "Không đủ credit",
    "ai.noCreditsDesc": "Bạn không đủ AI credit. Vui lòng nâng cấp gói.",
    "ai.notEnoughCredits": "Không đủ Credit — Nâng cấp gói",
    "ai.comingSoon": "Sắp ra mắt",
    "ai.feature.layoutSuggest": "AI Gợi ý bố cục",
    "ai.feature.layoutSuggestDesc": "Tạo bố cục nội thất tối ưu cho mọi loại phòng",
    "ai.feature.styleTransform": "AI Chuyển đổi phong cách",
    "ai.feature.styleTransformDesc": "Chuyển đổi phòng sang phong cách thiết kế khác",
    "ai.feature.productRecommend": "AI Gợi ý sản phẩm",
    "ai.feature.productRecommendDesc": "Gợi ý nội thất phù hợp với phòng của bạn",
    "ai.feature.budgetOptimize": "AI Tối ưu ngân sách",
    "ai.feature.budgetOptimizeDesc": "Tối ưu thiết kế nội thất trong ngân sách",
    "ai.feature.photoRender": "AI Render chân thực",
    "ai.feature.photoRenderDesc": "Tạo ảnh chân thực từ thiết kế phòng của bạn",
    "ai.feature.fullRedesign": "AI Thiết kế lại toàn bộ",
    "ai.feature.fullRedesignDesc": "Thiết kế lại hoàn toàn phòng với gợi ý AI",

    // AI Tool UI keys
    "ai.currentStyle": "Phong cách hiện tại",
    "ai.targetStyle": "Phong cách mong muốn",
    "ai.transform": "Chuyển đổi phong cách",
    "ai.transforming": "Đang chuyển đổi...",
    "ai.transformingDesc": "Đang áp dụng phong cách mới cho phòng của bạn",
    "ai.styleResults": "Kết quả chuyển đổi phong cách",
    "ai.tryAgain": "Thử lại",
    "ai.roomContext": "Bối cảnh phòng",
    "ai.preferences": "Sở thích",
    "ai.getRecommendations": "Nhận gợi ý",
    "ai.findingProducts": "Đang tìm sản phẩm...",
    "ai.recommendations": "Sản phẩm gợi ý",
    "ai.totalBudget": "Tổng ngân sách",
    "ai.priority": "Ưu tiên tối ưu",
    "ai.optimizeBudget": "Tối ưu ngân sách",
    "ai.optimizingBudget": "Đang tối ưu ngân sách...",
    "ai.budgetResults": "Kết quả tối ưu ngân sách",
    "ai.renderStyle": "Phong cách render",
    "ai.lighting": "Ánh sáng",
    "ai.resolution": "Độ phân giải",
    "ai.startRender": "Bắt đầu Render",
    "ai.rendering": "Đang render...",
    "ai.renderingDesc": "Đang tạo ảnh chân thực từ thiết kế của bạn",
    "ai.renderResult": "Render hoàn tất",
    "ai.renderAnother": "Render thêm",
    "ai.redesignScope": "Phạm vi thiết kế lại",
    "ai.designVision": "Tầm nhìn thiết kế",
    "ai.startRedesign": "Bắt đầu thiết kế lại",
    "ai.redesigning": "Đang thiết kế lại...",
    "ai.redesigningDesc": "AI đang tái thiết kế không gian của bạn",
    "ai.proposedChanges": "Thay đổi đề xuất",
    // AI Optimize (Editor)
    "ai.opt.title": "AI Tối ưu",
    "ai.opt.analyzeTitle": "Phân tích bố cục",
    "ai.opt.analyzeDesc": "AI sẽ phân tích cách sắp xếp nội thất và đề xuất cải thiện.",
    "ai.opt.objectsInRoom": "đồ vật trong phòng",
    "ai.opt.optimize": "Tối ưu bố cục",
    "ai.opt.addFirst": "Thêm nội thất trước để tối ưu",
    "ai.opt.analyzing": "Đang phân tích...",
    "ai.opt.analyzingDesc": "Kiểm tra luồng di chuyển và thẩm mỹ",
    "ai.opt.suggestionsFound": "đề xuất",
    "ai.opt.reanalyze": "Phân tích lại",
    "ai.opt.applied": "Đã áp dụng",
    "ai.opt.moveForFlow": "Cải thiện luồng di chuyển",
    "ai.opt.moveForFlowDesc": "Di chuyển nội thất sát tường để tạo không gian đi lại",
    "ai.opt.rotateAlign": "Căn chỉnh tốt hơn",
    "ai.opt.rotateAlignDesc": "Xoay nội thất hướng về trung tâm phòng",
    "ai.opt.addPlant": "Thêm cây xanh",
    "ai.opt.addPlantDesc": "Góc xa chưa tận dụng — thêm cây xanh cân bằng bố cục",

    // AI Layout Generator
    "aiGen.title": "AI Tạo bố cục",
    "aiGen.subtitle": "Tạo bố cục phòng tối ưu bằng AI",
    "aiGen.roomType": "Loại phòng",
    "aiGen.designStyle": "Phong cách thiết kế",
    "aiGen.dimensions": "Kích thước phòng",
    "aiGen.widthLabel": "Chiều rộng (m)",
    "aiGen.depthLabel": "Chiều sâu (m)",
    "aiGen.totalArea": "m² tổng",
    "aiGen.advanced": "Tùy chọn nâng cao",
    "aiGen.selected": "đã chọn",
    "aiGen.occupants": "Số người ở",
    "aiGen.budget": "Ngân sách",
    "aiGen.purpose": "Mục đích chính",
    "aiGen.selectMultiple": "(chọn nhiều)",
    "aiGen.mustHave": "Nội thất bắt buộc",
    "aiGen.customPrompt": "Yêu cầu tùy chỉnh",
    "aiGen.optional": "(tùy chọn)",
    "aiGen.promptPlaceholder": "VD: Tôi muốn góc đọc sách cạnh cửa sổ, TV đối diện sofa, và chỗ trải thảm yoga...",
    "aiGen.promptHint": "Mô tả sở thích, yêu cầu hoặc cách sắp xếp nội thất bạn muốn AI xem xét.",
    "aiGen.generate": "Tạo bố cục AI",
    "aiGen.generating": "Đang tạo bố cục",
    "aiGen.generatingDesc": "AI đang phân tích phòng và tạo cách sắp xếp nội thất tối ưu…",
    "aiGen.analyzingDim": "🔍 Phân tích kích thước",
    "aiGen.selectingFurn": "🪑 Chọn nội thất",
    "aiGen.optimizing": "📐 Tối ưu vị trí",
    "aiGen.suggestions": "Gợi ý AI",
    "aiGen.suggestionsDesc": "bố cục được tạo cho",
    "aiGen.regenerate": "Tạo lại",
    "aiGen.bestMatch": "Phù hợp nhất",
    "aiGen.apply": "Áp dụng",
    "aiGen.edit": "Chỉnh sửa",
    "aiGen.spaceAnalysis": "Phân tích không gian",
    "aiGen.spaceEfficiency": "Hiệu quả không gian",
    "aiGen.walkingPaths": "Lối đi",
    "aiGen.unusedArea": "Diện tích trống",
    "aiGen.furnitureDensity": "Mật độ nội thất",
    "aiGen.clear": "Thông thoáng",
    "aiGen.optimal": "Tối ưu",
    "aiGen.layoutApplied": "Đã áp dụng bố cục",

    // Plan & Credits
    "plan.plan": "Gói",
    "plan.credits": "Credit AI",
    "plan.creditsRemaining": "còn lại",
    "plan.creditsUsed": "đã dùng",
    "plan.currentPlan": "Gói hiện tại",
    "plan.viewPlans": "Xem các gói",
    "plan.free": "Miễn phí",
    "plan.basic": "Cơ bản",
    "plan.advanced": "Nâng cao",
    "plan.pro": "Chuyên nghiệp",
    "plan.perDay": "/ngày",
    "plan.noCredits": "Hết credit",
    "plan.buyMore": "Mua thêm Credit",

    // Mobile nav
    "mobile.home": "Trang chủ",
    "mobile.models": "Nội thất",
    "mobile.rooms": "Phòng",
    "mobile.profile": "Hồ sơ",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved === "vi" ? "vi" : "en") as Language;
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  }, []);

  const t = useCallback(
    (key: string) => translations[language][key] || key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
